Repository googleapis/java-mediatranslation, pull requests merged in 2020-06, with the labels that each got.

#69 chore: regenerate with updated protoc
  proto-google-cloud-mediatranslation-v1beta1/src/main/java/com/google/cloud/mediatranslation/v1beta1/StreamingTranslateSpeechConfig.java
  proto-google-cloud-mediatranslation-v1beta1/src/main/java/com/google/cloud/mediatranslation/v1beta1/StreamingTranslateSpeechRequest.java
  proto-google-cloud-mediatranslation-v1beta1/src/main/java/com/google/cloud/mediatranslation/v1beta1/StreamingTranslateSpeechResponse.java
  proto-google-cloud-mediatranslation-v1beta1/src/main/java/com/google/cloud/mediatranslation/v1beta1/StreamingTranslateSpeechResult.java
  proto-google-cloud-mediatranslation-v1beta1/src/main/java/com/google/cloud/mediatranslation/v1beta1/TranslateSpeechConfig.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#71 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#73 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#75 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#79 fix: migrate mediatranslation/v1beta1 to grpc_service_config
  google-cloud-mediatranslation/src/main/java/com/google/cloud/mediatranslation/v1beta1/stub/SpeechTranslationServiceStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#84 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#85 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-mediatranslation/pom.xml
  grpc-google-cloud-mediatranslation-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-mediatranslation-v1beta1/pom.xml
Labels: cla: yes

#92 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
