Repository googleapis/java-mediatranslation, pull requests merged in 2020-09, with the labels that each got.

#114 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: mediatranslation, cla: yes, context: full

#115 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: full

#127 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#129 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: mediatranslation, automerge, cla: yes
