Repository googleapis/java-mediatranslation, pull requests merged in 2020-08, with the labels that each got.

#100 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#102 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#105 tests: add system test for v1beta1
  google-cloud-mediatranslation/src/test/java/com/google/cloud/mediatranslation/v1beta1/it/ITSystemTest.java
Labels: cla: yes

#107 samples: add presubmit lint check
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#108 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#109 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
