Repository googleapis/java-mediatranslation, pull requests merged in 2021-05, with the labels that each got.

#280 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: mediatranslation, automerge, cla: yes

#282 chore: adding cloud-rad java xrefs
  .github/release-please.yml
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: partial

#284 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: full

#287 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: full

#288 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: mediatranslation, automerge, cla: yes

#291 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: full

#289 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  google-cloud-mediatranslation-bom/pom.xml
  google-cloud-mediatranslation/pom.xml
  owlbot.py
  pom.xml
  synth.py
  versions.txt
Labels: api: mediatranslation, automerge, cla: yes

#296 chore: regenerate README
  .github/generated-files-bot.yml
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: mediatranslation, automerge, cla: yes

#300 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: mediatranslation, automerge, cla: yes

#301 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: mediatranslation, automerge, cla: yes
