Repository googleapis/java-mediatranslation, pull requests merged in 2021-01, with the labels that each got.

#194 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: mediatranslation, cla: yes

#195 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: mediatranslation, automerge, cla: yes

#196 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: mediatranslation, automerge, cla: yes

#198 chore: update gapic-generator-java to 0.0.18
  google-cloud-mediatranslation/src/main/java/com/google/cloud/mediatranslation/v1beta1/SpeechTranslationServiceClient.java
  google-cloud-mediatranslation/src/main/java/com/google/cloud/mediatranslation/v1beta1/SpeechTranslationServiceSettings.java
  google-cloud-mediatranslation/src/main/java/com/google/cloud/mediatranslation/v1beta1/stub/GrpcSpeechTranslationServiceCallableFactory.java
  google-cloud-mediatranslation/src/main/java/com/google/cloud/mediatranslation/v1beta1/stub/GrpcSpeechTranslationServiceStub.java
  google-cloud-mediatranslation/src/main/java/com/google/cloud/mediatranslation/v1beta1/stub/SpeechTranslationServiceStub.java
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: full

#206 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: full

#207 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: mediatranslation, automerge, cla: yes
